# Generated by Django 3.2 on 2021-05-04 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('snsimage', models.ImageField(upload_to='')),
                ('good', models.IntegerField(blank=True, default=1, null=True)),
                ('read', models.IntegerField(blank=True, default=1, null=True)),
                ('readtext', models.TextField(blank=True, default='a', null=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
